### ISSUE TITLE
关于disentangle-VAE的问题

### ISSUE THREAD

**Issue by 3030xx-stack** [GlitteringAu/hello-world#1]
您好，看到您的名字是中文，所以就直接用中文题问了。
我想问一下，您在复现这套代码时是直接使用了作者training.sh中的参数吗？因为我看到--style_cof出现了两次，--samples-length也和train.py中对应不上。
很抱歉打扰您了，期待您的回复。

**Comment by PeGunter** [comment]
> 您好，看到您的名字是中文，所以就直接用中文题问了。 我想问一下，您在复现这套代码时是直接使用了作者training.sh中的参数吗？因为我看到--style_cof出现了两次，--samples-length也和train.py中对应不上。 很抱歉打扰您了，期待您的回复。

你好，这些参数并没有改动，但我尝试重新训练确实也出现了错误
`Traceback (most recent call last):
  File "train.py", line 79, in <module>
    train_loader, dataset = get_dataset(args.dataset_fp, batch_size=args.batch_size, num_utt=40)
  File "train.py", line 53, in get_dataset
    dataset = SpeechDatasetGVAE(dataset_fp, samples_length=64)
  File "/home/pjt/Disentangle-VAE-for-VC/preprocessing/dataset.py", line 76, in __init__
    self.utterance_fp = np.concatenate((self.utterance_fp, spk_utt), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)`
当时是可以训练的，你是否是同样的错误？

**Comment by 3030xx-stack** [comment]
我可以训练，没有报错。你之前训练多久，我算了一下，我这最起码要训练半个月。你这个错误应该是预处理没对上？如果可以的话可以添加好友一起讨论吗？

**Comment by PeGunter** [comment]
> 我可以训练，没有报错。你之前训练多久，我算了一下，我这最起码要训练半个月。你这个错误应该是预处理没对上？如果可以的话可以添加好友一起讨论吗？

你的问题已经解决了吗？是修改了什么地方呢，很久之前训练的这个项目，后来就没搞了哈哈，大概训练三四天吧，没有很久，我的QQ：838196094
